server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 111.231.255.138
    hostname: VM_0_6_centos
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
